name: Test & Release
on:
  push:
    branches:
      - develop
      - main
  pull_request: null

jobs:
  tests:
    name: Unit Tests
    runs-on: ubuntu-latest
    if: contains(toJson(github.event.commits.*.message), '[skip ci]') == false || github.ref == 'refs/heads/main'
    strategy:
      matrix:
        node: [12.x, 14.x, 16.x]
    steps:
      - name: ☁️ Checkout Project
        uses: actions/checkout@v2
      - name: 🔧 Setup node.js
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node }}
          cache: 'npm'
      - name: 📦 Install dependencies
        run: npm ci
      - name: 🐳 Pull alpine image (for unit tests)
        run: docker pull alpine
      - name: ⏳ Run tests
        run: npm run test

  coverage:
    name: Code Coverage / Lint
    runs-on: ubuntu-latest
    if: contains(toJson(github.event.commits.*.message), '[skip ci]') == false || github.ref == 'refs/heads/main'
    steps:
      - name: ☁️ Checkout Project
        uses: actions/checkout@v2
      - name: 🔧 Setup node.js
        uses: actions/setup-node@v2
        with:
          cache: 'npm'
      - name: 📦 Install dependencies
        run: npm ci
      - name: 🐳 Pull alpine image (for unit tests)
        run: docker pull alpine
      - name: 🔍 Run linter
        run: npm run lint
      - name: ⚙️ Build project
        run: npm run build-all

  license-checker:
    name: License Checker
    runs-on: ubuntu-latest
    if: contains(toJson(github.event.commits.*.message), '[skip ci]') == false || github.ref == 'refs/heads/main'
    steps:
      - name: ☁️ Checkout Project
        uses: actions/checkout@v2
      - name: 🔧 Setup node.js
        uses: actions/setup-node@v2
        with:
          cache: 'npm'
      - name: 📦 Install dependencies
        run: npm ci
      - name: 🕵️‍♀️ Run license checker
        run: npm run license-check

  release:
    name: Release
    runs-on: ubuntu-latest
    env:
      PUSH_TO_DOCKERHUB: ${{ (github.repository != 'sebbo2002/js-template') && (secrets.DOCKERHUB_TOKEN != null) }}
    needs:
      - coverage
      - tests
      - license-checker
    if: ${{ github.repository != 'sebbo2002/js-template' && (github.ref == 'refs/heads/main' || github.ref == 'refs/heads/develop') }}
    steps:
      - name: ☁️ Checkout Project
        uses: actions/checkout@v2
      - name: 🔧 Setup node.js
        uses: actions/setup-node@v2
        with:
          cache: 'npm'
      - name: 📦 Install dependencies
        run: npm ci
      - name: 📂 Create docs folder
        run: mkdir ./docs
      - name: 🐳 Pull alpine image (for unit tests)
        run: docker pull alpine
      - name: 🪄 Run semantic-release
        run: BRANCH=${GITHUB_REF#refs/heads/} npx semantic-release
        env:
          GH_REPO: ${{ github.repository }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          GH_OWNER: ${{ github.repository_owner }}
          GITHUB_NPM_CONFIG_REGISTRY: https://npm.pkg.github.com/
          GITHUB_NPM_TOKEN: ${{ secrets.GH_TOKEN }}
          PUBLIC_NPM_CONFIG_REGISTRY: https://registry.npmjs.org
          PUBLIC_NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
      - name: 🔃 Merge main back into develop
        if: ${{ github.ref == 'refs/heads/main' }}
        uses: everlytic/branch-merge@1.1.2
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          source_ref: 'main'
          target_branch: 'develop'
          commit_message_template: 'Merge branch {source_ref} into {target_branch} [skip ci]'
